[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
clmm_manager = "E9iJcnzprVCjrJiSVfPKVEqLvSN2jTn9qwKXJFhEUnrm"
solend_wrapper = "Cj2icEd2Zb8dzZQ6eEyUdTm5n86hBxD2KNU9qJtS9pSR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/victorgenin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
