[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
clmm_manager = "441hQCsxuqCJumMNPdGaZxBzTtuLbadAaH3hcnTufPZR"
solend_wrapper = "ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/victorgenin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
